site_name: PAYBIN API

copyright: Copyright &copy; 2022 paybin.io

theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: white
      accent: orange
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
    
extra_css:
  - stylesheets/extra.css
version:
    provider: mike
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences

nav:
  - Home: index.md 
  - Getting started:
    - 'Frame API': 'frame-api/url-generation.md'
    - 'Terms of Service': getting-started.md
  - 'Payment API':
    - Authentication: 'payment-api/authentication.md'
    - Methods: 'payment-api/api-methods.md'
    
  - Resource: 
    - Sample source codes: resources.md

# nav:
#     - Overview: 'index.md'
#     - 'Frame API': './Frame-API/*'
#     - 'Payment API': './Payment-API/'
#     - About:
#         - 'License': 'index.md'
#         - 'Release Notes': 'index.md'